### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by karfau** [jedmao/semantic-release-npm-github-config#10]
There are some dependency updates pending and when running the `npm install` commands recommended in the readme, there are warnings about missing per dependency since the version ranges of the plugins are limited to before `semantic-versioning@17`:

```
$ npm install --save-dev semantic-release @jedmao/semantic-release-npm-github-config
npm WARN @semantic-release/commit-analyzer@6.3.3 requires a peer of semantic-release@>=15.8.0 <16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @semantic-release/changelog@3.0.6 requires a peer of semantic-release@>=15.8.0 <16.0.0 || >=16.0.0-beta <17.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @semantic-release/release-notes-generator@7.3.5 requires a peer of semantic-release@>=15.8.0 <16.0.0 || >=16.0.0-beta <17.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @semantic-release/npm@5.3.5 requires a peer of semantic-release@>=15.9.0 <16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @semantic-release/github@5.5.8 requires a peer of semantic-release@>=15.8.0 <16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @semantic-release/git@7.0.18 requires a peer of semantic-release@>=15.4.0 <16.0.0 but none is installed. You must install peer dependencies yourself.

+ semantic-release@17.3.0
+ @jedmao/semantic-release-npm-github-config@1.0.9
```

Please let us know about your plans for this repo.

**Comment by natedunn** [comment]
Also curious about this @jedmao . Thank you for your insight here.

**Comment by jednano** [comment]
I’m unable to do open source any more, so no it’s not. Feel free to fork.

**Comment by karfau** [comment]
@jedmao Thx for the reply.
May I suggest to communicate this fact more clearly in the repo?
There are some options how to do that:
- You could keep this issue open and maybe even pin it.
- You could archive the repo.
- Add some text to the top of the README that indicates the repo status.

Thank you

**Comment by natedunn** [comment]
@jedmao Thanks for the communication. I also second @karfau suggestions. At the least adding a notice at the top of the readme would go a long way. 👍
